name : PYTHONAPP
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  AzureSubscription: 'serviceconnection-manual' # Name of the Service Connection
  ApiName: 'python-app'
  BuildId: $(Build.BuildId)
  ClusterResourceGroup: MyResourceGroup  
  ChartPackage: '$(Build.ArtifactStagingDirectory)/$(ApiName)-$(Build.BuildId).tgz'  
  ChartPath: $(ApiName)
  HelmVersion: 3.5.0
  K8sNamespace: '$(Apiname)-test'
  KubernetesCluster: 'myAKSCluster'
  ImageName: 'sumanthviswanadhuni/python-app:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - template: ./template/CI-steps.yaml
    - template: ./template/helm-install.yml   
    - template: ./template/helm-deploy.yml   
    - template: ./template/helm-deploy-upgrade.yml
