name : PYTHONAPP
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  AzureSubscription: 'serviceconnection-manual' # Name of the Service Connection
  ApiName: 'python-app'
  BuildId: $(Build.BuildId)
  BuildNumber: $(BuildNumber)
  ArtifactName: 'python-app'
  ClusterResourceGroup: MyResourceGroup  
  ChartPackage: '$(Build.ArtifactStagingDirectory)/$(ApiName)-$(Build.BuildId).tgz'  
  artifactStagingDirectory: $(Build.ArtifactStagingDirectory)
  ChartPath: $(ApiName)
  HelmVersion: 3.5.0
  K8sNamespace: '$(Apiname)-test'
  KubernetesCluster: 'myAKSCluster'
  Repository: 'sumanthviswanadhuni/$(ApiName)'
  ReleaseValuesFile: '$(ChartPath)/values.yaml'
  Releasechartfile: '$(ChartPath)/chart.yaml' 
  
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - template: ./Final-templates/DockerBuildandPush.yml
    - template: ./Final-templates/CreateHelmPackage.yml
      parameters:          
          azureSubscription: $(AzureSubscription)
          buildNumber: $(BuildNumber)
          clusterResourceGroup: $(ClusterResourceGroup)          
          chartPath: $(ChartPath)          
          kubernetesCluster: $(KubernetesCluster)        
          releaseValuesFile: $(ReleaseValuesFile)
          artifactStagingDirectory: $(Build.ArtifactStagingDirectory)
          artifactName: $(ArtifactName)
          helmVersion: $(HelmVersion)
    
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  #Variables:
   # ChartPackage: '$(Pipeline.Workspace)/python-app-3.5.0.tgz' 
   # ReleaseValuesFile: '$(Pipeline.Workspace)/python-app/values.yaml'

  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: 'ubuntu-latest'
    environment: "test"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: $(ArtifactName)
              downloadPath: '$(System.ArtifactsDirectory)'
            
          - template: ./Final-templates/DeployHelmPackage.yml           
            parameters:
              apiName: $(ApiName)
              azureSubscription: '$(AzureSubscription)'
              clusterResourceGroup: '$(ClusterResourceGroup)'
          #    chartPackage: '$(System.ArtifactsDirectory)/python-app/python-app-3.5.0.tgz'
              helmVersion: $(HelmVersion)
              k8sNamespace: $(K8sNamespace)
              kubernetesCluster: $(KubernetesCluster)
           #   releaseValuesFile: '$(System.ArtifactsDirectory)/python-app/values.yaml' 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
